Add fastq-scan v0.4.4
StaPH-B/docker-builds pull request #286
Opened 2022-01-29 01:49 UTC by kevinlibuit

- [ ] This comment contains a description of what is in the pull request.
Adding fastq-scan v0.4.4

This PR is to add a new version of a tool that already has a dockerfile 
- [ ] Build your own docker image using a Dockerfile
  - [ ] Directory structure should be name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. spades/3.12.0/Dockerfile)
  - [ ] Includes the recommended LABELS
- [ ] (Optional) Dockerfile is built with best practices and has been approved by a linter (such as https://hadolint.github.io/hadolint/)
- [ ] Edit main README.md
- [ ] Ensure tool is listed in Program_Licenses.md
- [ ] Create a simple container-specific README.md in the same directory as the Dockerfile (i.e. spades/3.12.0/README.md)
- [ ] Update GitHub actions workflow if needed
- [ ] Any files required for building are located in the same directory as the Dockerfile (i.e. spades/3.12.0/my_spades_tests.sh)
- [ ] Have successfully run the workflow "Test <program name> image" in your forked repository

2022-01-31 17:40 UTC, rpetit3 requested changes

2022-01-31 17:40 UTC, rpetit3 commented on fastq-scan/0.4.4/Dockerfile
> +LABEL software.version="0.4.3"
```suggestion
LABEL software.version="0.4.4"
```

2022-01-31 17:40 UTC, rpetit3 commented on fastq-scan/0.4.4/README.md
> +Main tool: [fastq-scan](quay.io/biocontainers/fastq-scan:0.4.4--h7d875b9_0)
```suggestion
Main tool: [fastq-scan](https://github.com/rpetit3/fastq-scan)
```

2022-02-01 15:38 UTC, kapsakcj commented
Thanks for the PR. Docker image builds successfully and does it pretty quickly. 

<details>

```
$ docker build -t kevin/fastq-scan:0.4.4 fastq-scan/0.4.4/
Sending build context to Docker daemon   5.12kB
Step 1/15 : FROM ubuntu:xenial
 ---> 065cf14a189c
Step 2/15 : ARG FASTQSCAN_VER="0.4.4"
 ---> Running in 41da4eaa1dce
Removing intermediate container 41da4eaa1dce
 ---> 073848aa65dd
Step 3/15 : LABEL base.image="ubuntu:xenial"
 ---> Running in 678911d58961
Removing intermediate container 678911d58961
 ---> e4a2680dda59
Step 4/15 : LABEL dockerfile.version="1"
 ---> Running in 083c7c3c9667
Removing intermediate container 083c7c3c9667
 ---> edf85e77d725
Step 5/15 : LABEL software="fastq-scan"
 ---> Running in d32c674923c5
Removing intermediate container d32c674923c5
 ---> 821797be1714
Step 6/15 : LABEL software.version="0.4.4"
 ---> Running in d5f662d0b246
Removing intermediate container d5f662d0b246
 ---> ebdec13e96ea
Step 7/15 : LABEL description="Output FASTQ summary statistics in JSON format"
 ---> Running in 6a9b96792354
Removing intermediate container 6a9b96792354
 ---> 273c8a24564d
Step 8/15 : LABEL website="https://github.com/rpetit3/fastq-scan"
 ---> Running in e70350d5ac65
Removing intermediate container e70350d5ac65
 ---> ee301080ac4d
Step 9/15 : LABEL license="https://github.com/rpetit3/fastq-scan/blob/master/LICENSE"
 ---> Running in 27083c63a436
Removing intermediate container 27083c63a436
 ---> b2edf0f004b6
Step 10/15 : LABEL maintainer="Robert A. Petit III"
 ---> Running in 5fa27bccdcb7
Removing intermediate container 5fa27bccdcb7
 ---> a93becdec682
Step 11/15 : LABEL maintainer.email="robert.petit@wyo.gov"
 ---> Running in aa8f21c1079f
Removing intermediate container aa8f21c1079f
 ---> 52c062f79f8c
Step 12/15 : RUN apt-get update && apt-get install -y  g++  make  jq  wget &&  apt-get autoclean && rm -rf /var/lib/apt/lists/*
 ---> Running in 20bd879de0dd
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [2051 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [15.9 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [984 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [8820 B]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [99.8 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [97.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [2560 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [16.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1544 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [26.2 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [10.9 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [12.7 kB]
Fetched 19.3 MB in 3s (6441 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  binutils ca-certificates cpp cpp-5 g++-5 gcc gcc-5 libasan2 libatomic1
  libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libgcc-5-dev libgmp10 libgomp1
  libidn11 libisl15 libitm1 liblsan0 libmpc3 libmpfr4 libmpx0 libonig2
  libquadmath0 libssl1.0.0 libstdc++-5-dev libtsan0 libubsan0 linux-libc-dev
  manpages manpages-dev openssl
Suggested packages:
  binutils-doc cpp-doc gcc-5-locales g++-multilib g++-5-multilib gcc-5-doc
  libstdc++6-5-dbg gcc-multilib autoconf automake libtool flex bison gdb
  gcc-doc gcc-5-multilib libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg
  libasan2-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg
  libmpx0-dbg libquadmath0-dbg glibc-doc libstdc++-5-doc make-doc man-browser
The following NEW packages will be installed:
  binutils ca-certificates cpp cpp-5 g++ g++-5 gcc gcc-5 jq libasan2
  libatomic1 libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libgcc-5-dev libgmp10
  libgomp1 libidn11 libisl15 libitm1 liblsan0 libmpc3 libmpfr4 libmpx0
  libonig2 libquadmath0 libssl1.0.0 libstdc++-5-dev libtsan0 libubsan0
  linux-libc-dev make manpages manpages-dev openssl wget
0 upgraded, 37 newly installed, 0 to remove and 0 not upgraded.
Need to get 41.4 MB of archives.
After this operation, 149 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libgmp10 amd64 2:6.1.0+dfsg-2 [240 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 libmpfr4 amd64 3.1.4-1 [191 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial/main amd64 libmpc3 amd64 1.0.3-1 [39.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libidn11 amd64 1.32-3ubuntu1.2 [46.5 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libssl1.0.0 amd64 1.0.2g-1ubuntu4.20 [1083 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 openssl amd64 1.0.2g-1ubuntu4.20 [492 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 ca-certificates all 20210119~16.04.1 [148 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/main amd64 manpages all 4.04-2 [1087 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 wget amd64 1.17.1-1ubuntu1.5 [299 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 binutils amd64 2.26.1-1ubuntu1~16.04.8 [2312 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 libisl15 amd64 0.16.1-1 [524 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 cpp-5 amd64 5.4.0-6ubuntu1~16.04.12 [7783 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/main amd64 cpp amd64 4:5.3.1-1ubuntu1 [27.7 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libcc1-0 amd64 5.4.0-6ubuntu1~16.04.12 [38.8 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libgomp1 amd64 5.4.0-6ubuntu1~16.04.12 [55.2 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libitm1 amd64 5.4.0-6ubuntu1~16.04.12 [27.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libatomic1 amd64 5.4.0-6ubuntu1~16.04.12 [8892 B]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libasan2 amd64 5.4.0-6ubuntu1~16.04.12 [265 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 liblsan0 amd64 5.4.0-6ubuntu1~16.04.12 [105 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libtsan0 amd64 5.4.0-6ubuntu1~16.04.12 [244 kB]
Get:21 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libubsan0 amd64 5.4.0-6ubuntu1~16.04.12 [95.3 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libcilkrts5 amd64 5.4.0-6ubuntu1~16.04.12 [40.0 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libmpx0 amd64 5.4.0-6ubuntu1~16.04.12 [9762 B]
Get:24 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libquadmath0 amd64 5.4.0-6ubuntu1~16.04.12 [131 kB]
Get:25 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libgcc-5-dev amd64 5.4.0-6ubuntu1~16.04.12 [2239 kB]
Get:26 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 gcc-5 amd64 5.4.0-6ubuntu1~16.04.12 [8612 kB]
Get:27 http://archive.ubuntu.com/ubuntu xenial/main amd64 gcc amd64 4:5.3.1-1ubuntu1 [5244 B]
Get:28 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libc-dev-bin amd64 2.23-0ubuntu11.3 [68.6 kB]
Get:29 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 linux-libc-dev amd64 4.4.0-210.242  [...]

2022-02-01 15:50 UTC, kapsakcj approved these changes
All looks good to me 👍 

docker image built successfully and tested great with the included test fastq file

2022-02-01 16:10 UTC, merged

2022-02-01 16:26 UTC, kapsakcj commented
OK docker image is ready on quay https://quay.io/repository/staphb/fastq-scan?tab=tags and dockerhub https://hub.docker.com/r/staphb/fastq-scan/tags

@kevinlibuit I'll let you delete the dev branch if you're finished with it