add freyja 1.3.7
StaPH-B/docker-builds pull request #391
Opened 2022-06-16 18:40 UTC by kevinlibuit

Pull Request (PR) checklist:
- [ ] Include a description of what is in this pull request in this message.
- [ ] The dockerfile successfully builds to a test target for the user creating the PR. (i.e. `docker build --tag samtools:1.15test --target test docker-builds/samtools/1.15` )
- [ ] Directory structure as name of the tool in lower case with special characters removed with a subdirectory of the version number (i.e. `spades/3.12.0/Dockerfile`)
   - [ ] (optional) All test files are located in same directory as the Dockerfile (i.e. `shigatyper/2.0.1/test.sh`)
- [ ] Create a simple container-specific [README.md](https://github.com/StaPH-B/docker-builds/blob/master/.github/workflow-templates/readme-template.md) in the same directory as the Dockerfile (i.e. `spades/3.12.0/README.md`)
   - [ ] If this README is longer than 30 lines, there is an explanation as to why more detail was needed
- [ ] Dockerfile includes the recommended [LABELS](https://github.com/StaPH-B/docker-builds/blob/master/dockerfile-template/Dockerfile#L8-L18) 
- [ ] Main [README.md](https://github.com/StaPH-B/docker-builds/blob/master/README.md) has been updated to include the tool and/or version of the dockerfile(s) in this PR
- [ ] [Program_Licenses.md](https://github.com/StaPH-B/docker-builds/blob/master/Program_Licenses.md) contains the tool(s) used in this PR and has been updated for any missing

2022-06-16 18:43 UTC, kevinlibuit commented
Nothing that needs to be addressed urgently, but just want to take note of this as it's relevant to this PR:
>  (optional) All test files are located in same directory as the Dockerfile (i.e. shigatyper/2.0.1/test.sh)

I wonder if there's a better practice for us here since that test dir is fully redundant in both `freyja/[1.3.4,1.3.7]` and I'd imagine it will be similarly so with other tools and test files

2022-06-16 19:01 UTC, kevinlibuit commented
Shoot. Failed tests. Closing until I resolve this

2022-06-16 19:52 UTC, kevinlibuit commented
@erinyoung just a heads up: the failures looked to be due to context still being set by a defined input that no longer exists (`path_to_context`). Updated this to use the parsed outputs (`./${{ steps.parse.outputs.tool }}/${{ steps.parse.outputs.version }}`)

2022-06-17 03:15 UTC, kapsakcj commented on freyja/1.3.7/Dockerfile
> +LABEL dockerfile.version="2"
please change dockerfile.version down to 1 since this is a new version of freyja

2022-06-17 03:26 UTC, kapsakcj requested changes
I'm going to request that we `wget` the files from the `/freyja/1.3.4/tests/` dir instead of duplicating.

Could you please make this change? Additionally delete the `/freyja/1.3.7/tests/` directory and files inside

2022-06-17 03:40 UTC, kapsakcj commented
Something like this for the BAM: `wget https://github.com/StaPH-B/docker-builds/blob/master/freyja/1.3.4/tests/Freyja_WWSC2.bam?raw=true -O Freyja_WWSC2.bam`

and this for the TSVs and fasta: `wget https://raw.githubusercontent.com/StaPH-B/docker-builds/master/freyja/1.3.4/tests/Freyja_depths.tsv`

2022-06-17 18:28 UTC, kapsakcj approved these changes

2022-06-17 18:28 UTC, kapsakcj commented
All looks good! I'll merge and deploy the docker image now

2022-06-17 18:29 UTC, merged